parameters:
    gm_redmine_user_provider.bridge.oauth.storage.class: VmDashboard\Infrastructure\OAuthBundle\Security\Storage\OAuthStorage

services:
    gm_redmine_user_provider.bridge.oauth.storage:
        class: "%gm_redmine_user_provider.bridge.oauth.storage.class%"
        arguments:
            - "@fos_oauth_server.client_manager"
            - "@fos_oauth_server.access_token_manager"
            - "@fos_oauth_server.refresh_token_manager"
            - "@fos_oauth_server.auth_code_manager"
            - "@fos_oauth_server.user_provider"
            - "@security.encoder_factory"
