orm:
    mappings:
        GmRedmineUserProviderBundle:
            type: yml
            prefix: GMaissa\RedmineUserProviderBundle\Model
            dir: 'Resources/config/persistence'
#            is_bundle: false
