parameters:
    gm_redmine_user_provider.api.client.default.class: GMaissa\RedmineUserProviderBundle\ApiClient\Adapter\RedmineClientAdapter
    gm_redmine_user_provider.factory.user.default.class: GMaissa\RedmineUserProviderBundle\Factory\UserFactory
    gm_redmine_user_provider.provider.class: GMaissa\RedmineUserProviderBundle\Security\Provider\RedmineUserProvider
    gm_redmine_user_provider.api_client_class: Redmine\Client
    gm_redmine_user_provider.repository.user.orm.class: GMaissa\RedmineUserProviderBundle\Repository\DoctrineUserRepository

services:
    gm_redmine_user_provider.api.client.default:
        class: "%gm_redmine_user_provider.api.client.default.class%"
        arguments:
            - "%gm_redmine_user_provider.redmine.url%"
        calls:
            - [setClientClass, ["%gm_redmine_user_provider.api_client_class%"]]

    gm_redmine_user_provider.factory.user.default:
        class: "%gm_redmine_user_provider.factory.user.default.class%"
        calls:
            - [setUserClass, ["%gm_redmine_user_provider.user_class%"]]

    gm_redmine_user_provider.provider:
        class: "%gm_redmine_user_provider.provider.class%"
        arguments:
            - "%gm_redmine_user_provider.redmine.allowed_domains%"
            - "@logger"
        calls:
            - [setUserFactory, ["@gm_redmine_user_provider.factory.user"]]
            - [setApiClient, ["@gm_redmine_user_provider.api.client"]]
