GMaissa\RedmineUserProviderBundle\Model\RedmineUser:
    type: mappedSuperclass
    repositoryClass: GMaissa\RedmineUserProviderBundle\Repository\Doctrine\Orm\UserRepository
    fields:
        username:
            column: username
            type: string
            length: 180
        email:
            column: email
            type: string
            length: 180
        enabled:
            column: enabled
            type: boolean
        password:
            column: password
            type: string
        roles:
            column: roles
            type: array
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
